# Generated by Django 3.0.2 on 2020-03-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='最後に買ってからの経過日数'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='最後に買った日'),
        ),
    ]
