# Generated by Django 3.0.2 on 2020-03-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20200321_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='days',
        ),
        migrations.AddField(
            model_name='shopping',
            name='buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='買う日'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='count',
            field=models.IntegerField(default=1, verbose_name='個数'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='past',
            field=models.IntegerField(blank=True, null=True, verbose_name='経過日数'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='name',
            field=models.CharField(max_length=256, verbose_name='商品'),
        ),
    ]
