# Generated by Django 3.0.2 on 2020-03-21 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20200322_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='買う日'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='最後に買った日'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='価格'),
        ),
    ]
